### ISSUE TITLE
Problem with IoT devices

### ISSUE THREAD

**Issue by SandTOfficial** [isuPatches/WiseFy#103] opened 2018-01-23 20:17 UTC
Hi, i'm working on an app for manage IoT devices, when i use your library all things work well (I think, for now), but the app doesn't connect the smartphone to my IoT device. I think that the problem is the absence of internet connection. What can i do, for make it fully functional? Thanks in advance.

P.S. I used this code for my app:
```java
       wisefy = new WiseFy.brains(this).logging(true).getSmarts();
        if (wisefy.isWifiEnabled() == TRUE){
            if(wisefy.isDeviceConnectedToWifiNetwork() == TRUE){
                 if (wisefy.isDeviceConnectedToSSID("ESP") == FALSE){
                     WifiInfo currentNetwork = wisefy.getCurrentNetwork();
                     lastinacc = currentNetwork.getSSID();
                     Toast.makeText(this, lastinacc, Toast.LENGTH_LONG).show();
                     wisefy.disconnectFromCurrentNetwork();
                     wisefy.connectToNetwork("ESP", 3000);
                }
            }else{
                wisefy.connectToNetwork("ESP", 3000);
            }
        }else{
            wisefy.enableWifi();
            wisefy.connectToNetwork("ESP", 3000);
        }

**Comment by isuPatches** [comment] 2018-01-23 21:33
@SandTOfficial Can you provide two details for me:

- The version of WiseFy you are using
- Any logs (a filter on WiseFy) should be good enough

My other initial thought is it could be a permissions issue.

**Comment by SandTOfficial** [comment] 2018-01-24 16:28
I'm using `wisefy-2.0.1`, and, excuse my ignorance,  how I can obtain the logs? For the permissions i used karumi's dexter library with this code:


```java    private void requestPermission() {
        Dexter.withActivity(MainActivity.this)
                .withPermissions(
                        Manifest.permission.INTERNET,
                        Manifest.permission.CHANGE_WIFI_STATE,
                        Manifest.permission.ACCESS_WIFI_STATE,
                        Manifest.permission.ACCESS_NETWORK_STATE,
                        Manifest.permission.ACCESS_FINE_LOCATION,
                        Manifest.permission.ACCESS_COARSE_LOCATION)
                .withListener(new MultiplePermissionsListener() {
            @Override public void onPermissionsChecked(MultiplePermissionsReport report) {/* ... */}
            @Override public void onPermissionRationaleShouldBeShown(List<PermissionRequest> permissions, PermissionToken token) {/* ... */}
        }).check();
    }

**Comment by isuPatches** [comment] 2018-01-25 15:12
Hey there, sorry for the delayed response.  Seems like you are using the latest version of WiseFy which is good.  

As for logs, they should appear in Logcat since you have logging enabled:

`wisefy = new WiseFy.brains(this).logging(true).getSmarts();`

Are you using Android Studio?  I believe you can filter on 'WiseFy' to see the logging I have added once you open up the Logcat window there.

I apologize, but I will most likely not get a chance to do an investigation into this until this weekend as it's not connected to my day job, but I promise I will help!

**Comment by isuPatches** [comment] 2018-01-29 02:46
Hey there! 

As promised I spent some time doing some investigation and making sure that the library was function as intended.

I made a few alterations to your code since there were some additional steps that are not needed:

```
 // Ensure WiFi is enabled
 if (wisefy.isWifiEnabled()) {
       wisefy.enableWifi();
}

// Check if we're connected to the desired network
if (wisefy.isDeviceConnectedToSSID("CantTouchThis5g")){
       return; // Early return
 }

// The following line will disconnect from any current network and switch to the desired network
wisefy.connectToNetwork("CantTouchThis5g", 3000);
```

When already connected to the desired SSID logcat shows me:

```
01-28 20:41:07.048 7743-7743/com.isupatches.wisefysample D/WiseFyConnection: Current SSID: CantTouchThis5g, Desired SSID: CantTouchThis5g
01-28 20:41:07.049 7743-7743/com.isupatches.wisefysample D/WiseFyConnection: Network is connected
```

When on a different SSID and having to switch logcat shows me:

```
01-28 20:43:55.131 8191-8191/? D/WiseFyConnection: Current SSID: CantTouchThis, Desired SSID: CantTouchThis5g
01-28 20:43:55.132 8191-8191/? D/WiseFy: Waiting 3000 to connect to network with ssid CantTouchThis5g
01-28 20:43:55.137 8191-8191/? D/WiseFySearch: SSID in list: CantTouchThis5g, SSID: CantTouchThis5g
01-28 20:43:55.247 8191-8191/? D/WiseFyConnection: Current SSID: <unknown ssid>, Desired SSID: CantTouchThis5g
01-28 20:43:56.248 8191-8191/com.isupatches.wisefysample D/WiseFyConnection: Current time: 1517193836247 / End time: 1517193838245 (waitToConnectToSSID)
01-28 20:43:56.251 8191-8191/com.isupatches.wisefysample D/WiseFyConnection: Current SSID: CantTouchThis5g, Desired SSID: CantTouchThis5g
01-28 20:43:56.251 8191-8191/com.isupatches.wisefysample D/WiseFyConnection: Network is connected
```

At this point I unfortunately can't do too much to help without seeing logs.  As you're working with IoT it may be very hard to remote debug without hardware but please leave some notes with logcat details when you get a chance.

**Comment by SandTOfficial** [comment] 2018-01-29 14:56
Hi, thanks for you time, i've tested the app with your code, but in the logcat nothing appears, and when the app starts up I see that my device disconnect from last network but after few seconds it reconnect to the same old network.

**Comment by isuPatches** [comment] 2018-01-29 15:07
@SandTOfficial Do you have a filter on your logcat?  Maybe you're searching via regex?  I would disable that and just search with the term WiseFy after making sure` .logging(true)` is set on your WiseFy instance.

Can you please confirm:

1. You have not denied any permissions (maybe try manually going to app -> permission settings)
2. That your device can see the network you are trying to connect to (i.e. do you see the network "ESP" listed if you manually go through Wifi settings)

What kind of Android device are you using?  (OS and model would both be helpful).

**Comment by SandTOfficial** [comment] 2018-01-29 15:56
No, i don't have any filter, I use .logging(true). I don't denied any permission. I see the ESP network in the wifi settings. I've a Huawei P8 Lite 2017 with Android 7.0.

**Comment by isuPatches** [comment] 2018-01-30 05:28
@SandTOfficial Will you please try with a non-IoT related network to see if you get the same result?  It's the only thing I can think of is if there's something with the device you are developing against.

**Comment by isuPatches** [comment] 2018-02-07 20:56
@SandTOfficial Any luck with a non-IoT network?  Unfortunately, I can't reproduce and may be forced to close this assuming it's the device and not the library (sorry...I really do wish I could be of more help).

**Comment by SandTOfficial** [comment] 2018-02-07 21:02
Excuse me, I didn't see the last message, maybe tomorrow i will give you an answer. Excuse me again.

**Comment by SandTOfficial** [comment] 2018-02-09 16:38
Hi, I've tested with a non-IoT network and all is OK, so the problem is the IoT device, probably for the absence of internet connection.

**Comment by madiazg** [comment] 2018-02-10 12:56
Hello, I have the same problem when I try to connect with my camera sony alpha 6000. Wisefy does not detect when I have connected to the camera (isConnected). I use wisefy 2.0.1 in android studio.
When I connect my cell phone to the Wi-Fi network of the camera, it indicates that no Internet access has been detected.

**Comment by madiazg** [comment] 2018-02-10 13:03
I have tried with:
     - isDeviceConnectedToWifiNetwork()
     - isDeviceConnectedToSSID()

**Comment by isuPatches** [comment] 2018-02-12 01:09
hmm...it is most likely related to something here:

```
WifiConfiguration wifiConfiguration = mWiseFySearch.findSavedNetworkByRegex(ssidToConnectTo);
if (wifiConfiguration != null) {
      mWiseFyPrerequisites.getWifiManager().disconnect();
      mWiseFyPrerequisites.getWifiManager().enableNetwork(wifiConfiguration.networkId, true);
      mWiseFyPrerequisites.getWifiManager().reconnect();
      return mWiseFyConnection.waitToConnectToSSID(ssidToConnectTo, timeoutInMillis);
}
```
and waitToConnectToSSID or isCurrentNetworkConnectedToSSID: 

```
boolean waitToConnectToSSID(String ssid, int timeoutInMillis) {
long currentTime;
long endTime = System.currentTimeMillis() + timeoutInMillis;
do {
      boolean result = isCurrentNetworkConnectedToSSID(ssid);
      if (result) {
            return true;
      }
      SleepUtil.sleep(1000);
      currentTime = System.currentTimeMillis();
      if (LogUtil.isLoggable(TAG, Log.DEBUG, mWiseFyConfiguration.isLoggingEnabled())) {
            Log.d(TAG, String.format("Current time: %d / End time: %d (waitToConnectToSSID)", currentTime, endTime));
      }
} while (currentTime < endTime);
return false;
```

2.0.1 version here fore reference:

https://github.com/isuPatches/WiseFy/blob/8ab3635a7bc410ae2d313ba7d9d826dcddb2e3e3/wisefy/src/main/java/com/isupatches/wisefy/WiseFy.java

https://github.com/isuPatches/WiseFy/blob/8ab3635a7bc410ae2d313ba7d9d826dcddb2e3e3/wisefy/src/main/java/com/isupatches/wisefy/WiseFyConnection.java

We can get into this state if:

- The network is not connected
- The network is not availabe
- The SSID does not match

Would either of you be willing to help by providing logs from a test version of the library? 

I would like to know if connected or available is the expected reponse along with the SSID of the current network.  It does not make much sense to me and could use some help understanding what part is breaking :)

Unfortunately my laptop is in for repairs, so it will be next weekend before I can take a stab at this again.  I want to thank both of you for reporting and being patient as we work to figure this out.

**Comment by madiazg** [comment] 2018-02-14 13:33
Hello,
I'm a novice in programming, so you'll have to tell me exactly what I have to do to help you. Also, my english is pretty bad.

**Comment by isuPatches** [comment] 2018-02-18 02:14
@madiazg Not a problem...I will explain what I'm looking for and attach screen shots and an APK to this issue...that way we can work through this together :)

**Comment by isuPatches** [comment] 2018-02-18 03:56
Okay!  I have posted steps here: https://github.com/isuPatches/WiseFy/wiki/Steps-for-isDeviceConnectedToSSID-debugging along with some screenshots.

Thank you again for assisting.  Please let me know what you find or if you have any questions.

**Comment by isuPatches** [comment] 2018-02-23 06:12
@madiazg @SandTOfficial Any update?

**Comment by SandTOfficial** [comment] 2018-02-23 14:04
I forget to say you that i re-writed the whole app, and now all work fine. I don't know why but now, as already said, all work fine.

**Comment by isuPatches** [comment] 2018-02-24 19:03
Thank you!

**Closed** 2018-02-24 19:07 UTC
Labels: 2.x, Requires Discussion
