### ISSUE TITLE
not valid hex string

### ISSUE THREAD

**Issue by tinchoz49** [isuPatches/WiseFy#105] opened 2018-05-17 22:08 UTC
Hi @isuPatches! how are you? 

First, thank you for your work on this library, it was something really helpful in our project.

We are having an unusual issue for OnePlus 3T devices when we try to add a wifi network WPA2.

Here is the log:

```
05-17 17:52:41.627 1273-1750/? E/WifiConnectivityManager: Invalid max BSSID blacklist size:  0
05-17 17:52:41.761 1273-9551/? E/WifiService: not valid hex string: invalid char: V
05-17 17:52:41.761 1273-9551/? E/WifiService: SSID is invalid, SSID = VAMOSCUTCSA
05-17 17:52:41.761 1273-9551/? E/WifiService: bad network configuration
05-17 17:52:41.762 16533-25137/? E/WiseFy: Failed to add network
05-17 17:52:41.772 2694-24478/? W/Conscrypt: Could not set socket write timeout: java.lang.reflect.InvocationTargetException
05-17 17:52:41.773 2694-24478/? W/Conscrypt:     at java.lang.reflect.Method.invoke(Native Method)
05-17 17:52:41.773 2694-24478/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@12673023@12.6.73 (040400-194189626):13)
05-17 17:52:41.773 2694-24478/? W/Conscrypt: Caused by: android.system.ErrnoException: setsockopt failed: EBADF (Bad file descriptor)
05-17 17:52:41.773 2694-24478/? W/Conscrypt:     at libcore.io.Linux.setsockoptTimeval(Native Method)
05-17 17:52:41.773 2694-24478/? W/Conscrypt:     at libcore.io.ForwardingOs.setsockoptTimeval(ForwardingOs.java:173)
05-17 17:52:41.805 1273-9551/? E/WifiService: not valid hex string: invalid char: V
05-17 17:52:41.805 1273-9551/? E/WifiService: SSID is invalid, SSID = VAMOSCUTCSA
05-17 17:52:41.805 1273-9551/? E/WifiService: bad network configuration
05-17 17:52:41.805 16533-25137/? E/WiseFy: Failed to add network
05-17 17:52:41.899 2694-24478/? W/Conscrypt: Could not set socket write timeout: java.lang.reflect.InvocationTargetException
05-17 17:52:41.900 2694-24478/? W/Conscrypt:     at java.lang.reflect.Method.invoke(Native Method)
05-17 17:52:41.900 2694-24478/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@12673023@12.6.73 (040400-194189626):13)
05-17 17:52:41.900 2694-24478/? W/Conscrypt: Caused by: android.system.ErrnoException: setsockopt failed: EBADF (Bad file descriptor)
05-17 17:52:41.900 2694-24478/? W/Conscrypt:     at libcore.io.Linux.setsockoptTimeval(Native Method)
05-17 17:52:41.900 2694-24478/? W/Conscrypt:     at libcore.io.ForwardingOs.setsockoptTimeval(ForwardingOs.java:173)
05-17 17:52:42.630 24728-25059/? W/awcn.SessionCenter: |[seq:umeng:564ef50667e58e33e70021d1] app background, forbid to create accs session
05-17 17:52:42.631 24728-25059/? E/awcn.SessionCenter: |[seq:umeng:564ef50667e58e33e70021d1] [Get]connect exception errMsg:accs session connecting forbidden in background url:https://umengacs.m.taobao.com
05-17 17:52:42.631 24728-25059/? E/accs.InAppConn_umeng:564ef50667e58e33e70021d1:  reSend dataid:2 retryTimes:3
05-17 17:52:42.635 24728-25059/? E/accs.InAppConn_umeng:564ef50667e58e33e70021d1:  cancel customDataId:ctrl_bindapp
05-17 17:52:43.110 1273-1750/? W/WifiConfigManager: Looking up network with invalid networkId -1
05-17 17:52:43.116 1273-1750/? W/WifiConfigManager: Looking up network with invalid networkId -1
05-17 17:52:43.119 997-997/? W/wificond: Scan is not started. Ignore abort request
05-17 17:52:43.156 1273-1304/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } to com.cardinalblue.piccollage.google/com.adobe.creativesdk.aviary.internal.cds.CdsReceiver
05-17 17:52:43.442 1273-9550/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } to com.cardinalblue.piccollage.google/com.adobe.creativesdk.aviary.internal.cds.CdsReceiver
05-17 17:52:43.463 1273-9550/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } to com.cardinalblue.piccollage.google/com.adobe.creativesdk.aviary.internal.cds.CdsReceiver
05-17 17:52:43.466 542-542/? E/WifiHAL: wifi_get_packet_filter_capabilities: requestResponse() error: -1
05-17 17:52:43.467 1273-1750/? E/WifiVendorHal: getApfCapabilities(l.1577) failed {.code = ERROR_UNKNOWN, .description = unknown}
05-17 17:52:43.488 1273-9551/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } to com.cardinalblue.piccollage.google/com.adobe.creativesdk.aviary.internal.cds.CdsReceiver
05-17 17:52:43.497 2177-2177/? E/wpa_supplicant: wpa_driver_nl80211_driver_cmd: failed to issue private commands
05-17 17:52:43.497 1273-1750/? E/SupplicantStaIfaceHal: ISupplicantStaIface.addRxFilter failed: FAILURE_UNKNOWN, 
05-17 17:52:44.638 24728-25059/? W/awcn.SessionCenter: |[seq:umeng:564ef50667e58e33e70021d1] app background, forbid to create accs session
05-17 17:52:44.638 24728-25059/? E/awcn.SessionCenter: |[seq:umeng:564ef50667e58e33e70021d1] [Get]connect exception errMsg:accs session connecting forbidden in background url:https://umengacs.m.taobao.com
05-17 17:52:44.650 24728-25059/? E/accs.InAppConn_umeng:564ef50667e58e33e70021d1:  reSend dataid:2 retryTimes:4
05-17 17:52:44.661 24728-25059/? E/accs.InAppConn_umeng:564ef50667e58e33e70021d1:  cancel customDataId:ctrl_bindapp
05-17 17:52:44.728 1273-1304/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } to com.cardinalblue.piccollage.google/com.adobe.creativesdk.aviary.internal.cds.CdsReceiver
05-17 17:52:44.765 1273-1304/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } to com.cardinalblue.piccollage.google/com.adobe.creativesdk.aviary.internal.cds.CdsReceiver
05-17 17:52:44.824 1273-1750/? E/WifiStateMachine: Did not find remoteAddress {10.5.31.254} in /proc/net/arp
05-17 17:52:44.826 1273-9551/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } to com.cardinalblue.piccollage.google/com.adobe.creativesdk.aviary.internal.cds.CdsReceiver
05-17 17:52:44.878 2276-2369/? W/QCNEJ: |CORE| network available: 154
05-17 17:52:44.887 2276-2369/? W/QCNEJ: |CORE| onAvailable: bind the process to WIFI
05-17 17:52:44.899 1273-1747/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:967 com.android.server.net.NetworkPolicyManagerService.broadcastDataUsageAlarm:4518 com.android.server.net.NetworkPolicyManagerService.updateNotificationsNL:1173 com.android.server.net.NetworkPolicyManagerService$8.onReceive:986 android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_53427:1339 
05-17 17:52:44.923 1273-2270/? E/GnssLocationProvider: updateNetworkAvailability failed
05-17 17:52:44.962 1273-1747/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:967 com.android.server.net.NetworkPolicyManagerService.broadcastDataUsageAlarm:4518 com.android.server.net.NetworkPolicyManagerService.updateNotificationsNL:1173 com.android.server.net.NetworkPolicyManagerService$8.onReceive:986 android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_53427:1339 
05-17 17:52:44.982 995-1186/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'INTERFACE' not found
05-17 17:52:44.982 995-1186/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'STATE' not found
05-17 17:52:44.982 995-1186/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
05-17 17:52:44.982 995-1186/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
05-17 17:52:45.004 1004-2271/? E/IzatSvc_ComboNetworkProvider: Exiting with error proc line 208 "1"
05-17 17:52:45.051 540-1721/? E/qti_sensors_hal: sendEnableReq:sensor(android.sensor.significant_motion) Sending enable to svc no:40
05-17 17:52:45.064 22324-22635/? E/accs.SilenceConn_umeng:564ef50667e58e33e70021d1:  0 spdySessionCloseCallback, errorCode:-2032
05-17 17:52:45.065 22324-22635/? E/accs.SilenceConn_umeng:564ef50667e58e33e70021d1:  0 notifyStatus:DISCONNECTED
05-17 17:52:45.071 2694-24650/? E/WakeLock: release without a matched acquire!
05-17 17:52:45.144 4718-24724/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1477 android.content.ContextWrapper.startService:645 com.oneplus.security.network.trafficalarm.TrafficUsageAlarmIntentService.startService:73 com.oneplus.security.network.trafficalarm.TrafficUsageAlarmReceiver$1.doInBackground:60 com.oneplus.security.network.trafficalarm.TrafficUsageAlarmReceiver$1.doInBackground:32 
05-17 17:52:45.144 2694-24478/? W/ctxmgr: [AclManager]No 2 for (accnt=account#1047505475#, com.google.android.gms(10010):UserLocationProducer, vrsn=12673000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2694). Was: 2 for 1, account#1047505475#
05-17 17:52:45.145 4718-24726/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1477 android.content.ContextWrapper.startService:645 com.oneplus.security.network.trafficalarm.TrafficUsageAlarmIntentService.startService:73 com.oneplus.security.network.trafficalarm.TrafficUsageAlarmReceiver$1.doInBackground:60 com.oneplus.security.network.trafficalarm.TrafficUsageAlarmReceiver$1.doInBackground:32 
05-17 17:52:45.213 2694-25190/? E/WakeLock: release without a matched acquire!
05-17 17:52:45.218 2694-25190/? E/WakeLock: release without a matched acquire!
0
```

**Comment by isuPatches** [comment] 2018-05-18 14:25
Hi there!  Thanks for reporting to improve the library.

Hmm...this is interesting...

```
05-17 17:52:41.761 1273-9551/? E/WifiService: not valid hex string: invalid char: V
05-17 17:52:41.761 1273-9551/? E/WifiService: SSID is invalid, SSID = VAMOSCUTCSA
05-17 17:52:41.761 1273-9551/? E/WifiService: bad network configuration
```

The network is not being created because of the network configuration...specifically the SSID.  Does the same network SSID work on other devices?  

I will do two things over the weekend:

1. Investigate rules for WPA2 network SSIDs
2. Try to replicate on various brands, although it could be specific to OnePlus.

**Comment by tinchoz49** [comment] 2018-05-18 14:37
Hi @isuPatches !

We try the same network on a Samsung J7, Xiaomi, Alcatel and Moto g4 and it works.

Something that I didn't test was trying to add a different network (because as you said, maybe is the network configuration). I will try that case today.

Thanks for your help!

**Comment by tinchoz49** [comment] 2018-05-21 18:28
Hi @isuPatches! we did a test with another network and we got the same error.

**Comment by isuPatches** [comment] 2018-05-30 13:44
Hey @tinchoz49 I have been thinking on this for the past week.  I apologize for not responding sooner.  I believe the issue is with the OnePlus.  My proposal at this time is to add documentation about this issue as a known limitation as I'm uncertain we can work around what the OnePlus is thinking.  I investigated and found many issues of the OnePlus and connecting to a created network so for now I think I am going to close this issue.

I apologize and hope you continue to use the library.

**Closed by isuPatches** 2018-05-30 13:44 UTC
Labels: Needs Investigation, Requires Discussion

**Comment by tinchoz49** [comment] 2018-05-30 13:46
of course, I will keep using it :) thanks for taking the time to check this issue.
